---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 15672
          name: vpromq01-port
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: rmq-pass
              name: app-secret
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
      
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app: vpromq01
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP

